protected/models/PriceRequest.php
<?php

/**
 * This is the model class for table "price_request".
 *
 * The followings are the available columns in table 'price_request':
 * @property integer $id
 * @property string $create_time
 * @property string $update_time
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property integer $section_id
 * @property string $status
 *
 * The followings are the available model relations:
 * @property Sections $section
 * @property RequestFiles[] $requestFiles
 */
class PriceRequest extends CActiveRecord
{
        public $statuses = array(
            'new' => 'Необработано',
            'complete' => 'Обработано',
            'closed' => 'Закрыто',
        );
        
        public $upload;
        public $files;

        /**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return PriceRequest the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'price_request';
	}
        
        public function defaultScope() 
        {
            return array(
                'order' => 'id DESC',
            );
        }

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
                        array('name, phone, email', 'required'),
                        array('status', 'default', 'value' => 'new'),
                        array('email', 'email'),
			array('section_id', 'numerical', 'integerOnly'=>true),
			array('name, phone, email', 'length', 'max'=>45),
			array('status', 'length', 'max'=>8),
			array('create_time, update_time', 'safe'),
//                        array('files', 'file', 
//                            'allowEmpty' => true,
//                            'maxSize' => 10 * 1024 * 1024,
//                            'maxFiles' => 1,
//                            'types' => 'doc, docx, xls, pdf, ppt, jpg, png, zip, rar, jpeg',
//                            'message' => 'Размер файлов не может превышать 10 Мб'
//                        ),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, create_time, update_time, name, phone, email, section_id, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
//			'section' => array(self::BELONGS_TO, 'Sections', 'section_id'),
                        'section' => array(self::BELONGS_TO, 'Services', 'section_id'),
			'requestFiles' => array(self::HAS_MANY, 'RequestFiles', 'request_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Номер заявки',
			'create_time' => 'Дата получения заявки',
			'update_time' => 'Update Time',
			'name' => 'Фамилия и имя',
			'phone' => 'Телефон',
			'email' => 'Email',
			'section_id' => 'Выберите раздел',
			'status' => 'Статус',
                        'sectionName' => 'Услуга',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('create_time',$this->create_time,true);
		$criteria->compare('update_time',$this->update_time,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('phone',$this->phone,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('section_id',$this->section_id);
		$criteria->compare('status',$this->status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        public function behaviors()
        {
            return array(
                'CTimestampBehavior' => array(
                    'class' => 'zii.behaviors.CTimestampBehavior',
                ),
//                'uploadedFile'=>array(
//                    'class' => 'application.components.UploadableMultipleFileBehavior',
//                    'savePathAlias' => 'webroot.uploaded.request_files.' . $this->id,
//                    'fileTypes' => 'doc, docx, xls, pdf, ppt, jpg, png, zip, rar',
//                    'attributeName' => 'files',
//                ),
            );
        }
        
        public function getSectionName()
        {
            if(isset($this->section))
                return $this->section->title;
            return false;
        }
        
        public function beforeSave() 
        {
            if(parent::beforeSave()){
                if(!$this->_addFiles()){
//                    $this->requestFiles = array();
                    return false;
                }
                
                $this->_deleteFiles();
            }
            
            return true;
        }
        
        public function afterSave() 
        {
            parent::afterSave();
            $this->_saveFiles();
        }
        
        public function beforeDelete() 
        {
            parent::beforeDelete();
            
            foreach ($this->requestFiles as $item)
                if(is_object($item)) $item->delete();
            
            return true;
        }
        
        protected function _addFiles()
        {
            $i = 0;
            $files = array();
            while($upload = CUploadedFile::getInstance('RequestFiles', "file[$i]")){
                $file = new RequestFiles();
                $file->index = $i;
                $file->request_id = $this->id;
                $file->file = $upload->name;
                $file->scenario = 'multiple';
                $files[] = $file;
                $i++;
            }
            $this->requestFiles = $files;
            
            $valid = true;
            foreach ($this->requestFiles as $file){
                $valid = $file->validate() && $valid;
                if(!$valid){
                    $this->addError('upload', $file->getError('file'));
                    return false;
                }
            }
            return $valid;
        }
        
        public function _saveFiles()
        {
            $folder = YiiBase::getPathOfAlias('webroot.uploaded.request_files.'.$this->id);
            if (!file_exists($folder))
                mkdir($folder, 0, true);
            
            foreach ($this->requestFiles as $file){
                if(!$file->request_id) $file->request_id = $this->id;
                $file->disableBehavior('uploadedFile');
                
                $file->attachBehavior('uploadableFile', array(
                    'class' => 'application.components.UploadableFileBehavior',
                    'savePathAlias' => 'webroot.uploaded.request_files.' . $this->id,
                    'fileTypes' => 'doc, docx, xls, pdf, ppt, jpg, png, zip, rar, jpeg',
                ));
                $file->save();
            }
        }

        protected function _deleteFiles()
        {
            if(isset($_POST['RequestFiles']['delete']))
                foreach($_POST['RequestFiles']['delete'] as $item){
                    foreach($item as $id => $value){
                        if ($value){
                            $file = RequestFiles::model()->deleteByPk($id);
                            if(is_object($file)) $file->delete();
                        }
                    }
                }
        }
        
        public function getSectionsList()
        {
//            return Sections::model()->getList('request');
            return Services::model()->getList();
        }
}

protected/controllers/PricerequestController.php
<?php

class PricerequestController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
                    'accessControl', // perform access control for CRUD operations
                    'postOnly + delete', // we only allow deletion via POST request
                    'BackEndSettings + create, update, admin, delete',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('create','update','admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new PriceRequest;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['PriceRequest']))
		{
			$model->attributes=$_POST['PriceRequest'];
			if($model->save()){
                            if(isset($_POST['apply']))
                                    $this->redirect(array('update', 'id' => $model->id));
                                else
                                    $this->redirect(array('admin'));
                        }
		}

		$this->render('form',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['PriceRequest']))
		{
			$model->attributes=$_POST['PriceRequest'];
			if($model->save()){
                            if(isset($_POST['apply']))
                                    $this->redirect(array('update', 'id' => $model->id));
                                else
                                    $this->redirect(array('admin'));
                        }
		}

		$this->render('form',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('PriceRequest');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new PriceRequest('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['PriceRequest']))
			$model->attributes=$_GET['PriceRequest'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return PriceRequest the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=PriceRequest::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param PriceRequest $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='price-request-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/pricerequest/admin.php
<?php
/* @var $this PriceRequestController */
/* @var $model PriceRequest */
?>

<div class="row-fluid">
    <div class="page-header container-fluid">
	<h1 class="pull-left"><?=$this->pageTitle; ?></h1>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'url' => array('create'),
            'label' => '&nbsp;Добавить',
            'icon' => 'plus white',
            'type'=>'primary',
            'encodeLabel' => false,
            'htmlOptions' => array(
                'class' => 'pull-right',
            'style' => 'margin-top:10px; margin-bottom:10px'))
        ); ?>
    </div>
</div>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
    'type'=>'striped bordered condensed',
    'dataProvider'=>$model->search(),
    'template'=>"{items}\n{pager}",
    'filter' => $model,
    'columns'=>array(
        'id',
        'name',
        array(
            'name' => 'create_time',
            'filter' => false,
            'type' => 'date',
        ),
        array(
            'name' => 'status',
            'filter' => $model->statuses,
            'value' => '$data->statuses[$data->status]',
        ),
        array(
            'class' => 'bootstrap.widgets.TbButtonColumn',
            'htmlOptions' => array('style'=>'width: 50px', 'class' => 'button-distance'),
            'template' => '{update}{delete}',
        ),
    ),
));

protected/views/pricerequest/form.php
<?php
/* @var $this DefaultController */
/* @var $model Statpages */
/* @var $form CActiveForm */
?>

<div class="row-fluid">
    <div class="page-header container-fluid">
	<h1 class="pull-left"><?= $this->pageTitle; ?></h1>
    </div>
</div>

<div class="row-fluid" id="grid">
    <?php $form=$this->beginWidget('AdminForm', array(
        'id'=>'candidates-form',
        'type' => 'horizontal',
	'enableAjaxValidation'=>false,
        'htmlOptions' => array(
            'enctype' => 'multipart/form-data',
        )
    )); ?>
    <?= $form->errorSummary($model); ?>
    <?= $form->dropDownListRow($model, 'status', $model->statuses, array(
        'empty' => '',
        'class'=>'span5'
        )); ?>
    <?php $this->widget('bootstrap.widgets.TbDetailView', array(
        'data'=>$model,
        'attributes'=>array(
            array(
                'name' => 'create_time',
                'type' => 'date',
            ),
            'name',
            'phone',
            'email',
            'sectionName'
        ),
    )); ?>
    <? /* ?>
    <?= $form->textFieldRow($model, 'name', array('class'=>'span5')); ?>
    <?= $form->textFieldRow($model, 'phone', array('class'=>'span5')); ?>
    <?= $form->textFieldRow($model, 'email', array('class'=>'span5')); ?>
    <?= $form->dropDownListRow($model, 'section_id', $model->sectionsList, array(
        'empty' => '',
        'class'=>'span5'
    )); ?>
    <? */ ?>
    <fieldset>
        <legend>Файлы</legend>
        <? /*= $form->fileFieldRow(new RequestFiles(), 'file[]', array(
            'multiple' => 'multiple',
        )) */?>
        <?php if(count($model->requestFiles)): ?>
            <?php foreach ($model->requestFiles as $item): ?>
                <div class='control-group'>
                    <div class='controls'>
                        <?= CHtml::link($item->file, $item->fileUrl, array(
                            'target' => '_blank',
                        )) ?>
                        <label class="checkbox">
                            <input name="<?= get_class($item) ?>[delete][file][<?= $item->id ?>]" id="File_delete" value="1" type="checkbox">
                            Удалить файл
                        </label>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <p>Нет загруженных файлов</p>
        <?php endif; ?>
    </fieldset>
    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>'Сохранить',
            'htmlOptions' => array('name' => 'save'))
        ); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'label'=>'Применить',
            'htmlOptions' => array('name' => 'apply'))
        ); ?>
    </div>
    <?php $this->endWidget(); ?>
</div>

protected/views/pricerequest/index.php
<?php
/* @var $this PriceRequestController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Price Requests',
);

$this->menu=array(
	array('label'=>'Create PriceRequest', 'url'=>array('create')),
	array('label'=>'Manage PriceRequest', 'url'=>array('admin')),
);
?>

<h1>Price Requests</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/pricerequest/view.php
<?php
/* @var $this PriceRequestController */
/* @var $model PriceRequest */

$this->breadcrumbs=array(
	'Price Requests'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List PriceRequest', 'url'=>array('index')),
	array('label'=>'Create PriceRequest', 'url'=>array('create')),
	array('label'=>'Update PriceRequest', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete PriceRequest', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage PriceRequest', 'url'=>array('admin')),
);
?>

<h1>View PriceRequest #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'create_time',
		'update_time',
		'name',
		'phone',
		'email',
		'section_id',
		'status',
	),
)); ?>